INSERT INTO countries(name, iso) VALUES ('Afghanistan', 'AFG');
INSERT INTO countries(name, iso) VALUES ('Aland Islands', 'ALA');
INSERT INTO countries(name, iso) VALUES ('Albania', 'ALB');
INSERT INTO countries(name, iso) VALUES ('Bahrain', 'BHR');
INSERT INTO countries(name, iso) VALUES ('Barbados', 'BRB');
INSERT INTO countries(name, iso) VALUES ('Belarus', 'BLR');
INSERT INTO countries(name, iso) VALUES ('Cameroon', 'CMR');
INSERT INTO countries(name, iso) VALUES ('Canada', 'CAN');
INSERT INTO countries(name, iso) VALUES ('Denmark', 'DNK');
INSERT INTO countries(name, iso) VALUES ('Jamaica', 'JAM');