INSERT INTO users(email, citizenship_country_id) VALUES ('tim@gmail.com', 1);
INSERT INTO users(email, citizenship_country_id) VALUES ('ruthann@gmail.com', 2);
INSERT INTO users(email, citizenship_country_id) VALUES ('lianne@gmail.com', 3);
INSERT INTO users(email, citizenship_country_id) VALUES ('jordan@gmail.com', 4);
INSERT INTO users(email, citizenship_country_id) VALUES ('lorrie@gmail.com', 5);
INSERT INTO users(email, citizenship_country_id) VALUES ('barney@gmail.com', 5);
INSERT INTO users(email, citizenship_country_id) VALUES ('clint@gmail.com', 5);
INSERT INTO users(email, citizenship_country_id) VALUES ('john@gmail.com', 5);
INSERT INTO users(email, citizenship_country_id) VALUES ('genna@gmail.com', 5);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'rosita@gmail.com', 5);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'carita@gmail.com', 5);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'sandra@gmail.com', 6);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'shavon@gmail.com', 6);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'dave@gmail.com', 6);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'towanda@gmail.com', 6);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'maddie@gmail.com', 6);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'lashaun@gmail.com', 7);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'magen@gmail.com', 8);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'rudolf@gmail.com', 8);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'latrisha@gmail.com', 8);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'gloria@gmail.com', 8);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'isaias@gmail.com', 8);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'ivette@gmail.com', 8);
INSERT INTO users(email, citizenship_country_id) VALUES ( 'elizabet@gmail.com', 9);